name: sticker_maker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.1.0
  image: ^4.1.7     # 用來切割圖片
  archive: ^3.4.10  # 用來打包 ZIP

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 註冊資源區塊
  assets:
    - assets/
